name: 360CafesAndOutlets

on:
  push:
    branches: [ main ]

jobs:
  # Build & Deploy Shop Owner Web App
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          cd frontend/shop_owner_app
          flutter pub get
      - name: Build Web
        run: |
          cd frontend/shop_owner_app
          flutter build web --release
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAFE_360 }}'
          projectId: app-1aec6
          channelId: live
